name: Test
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        rust: [ stable ]

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test --verbose
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.65.0
          components: clippy
      - name: Clippy checks
        run: cargo clippy --verbose
